# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster

WORKDIR C:\Users\yido6\Documents\Uni\Level 7\SnPip\App 1.0\integrated_search_app

COPY requirements.txt requirements.txt

RUN pip3 install -r requirements.txt

COPY . .

ENV FLASK_APP=main.py

CMD [ "python3", "-m" , "flask", "run", "-h", "0.0.0.0", "-p", "5000"]
